### ISSUE TITLE
Add support for 'visibility' per version

### ISSUE THREAD

**Issue by tobfisch** [SovereignCloudStack/openstack-image-manager#168]
I would like to add support of setting the visibility per version. 
Maybe per adding a new attribut, to the versions list: 
```
  - name: Ubuntu 20.04
    format: qcow2
    login: ubuntu
    min_disk: 8
    min_ram: 512
    status: active
    visibility: public
    multi: true
    meta:
      architecture: x86_64
      hw_disk_bus: scsi
      hw_rng_model: virtio
      hw_scsi_model: virtio-scsi
      hw_watchdog_action: reset
      os_distro: ubuntu
      os_version: '20.04'
    tags: []
    versions:
      - version: '20210513.1'
        url: https://cloud-images.ubuntu.com/focal/20210513.1/focal-server-cloudimg-amd64.img
        visibility: private
      - version: '20210518'
        url: https://cloud-images.ubuntu.com/focal/20210518/focal-server-cloudimg-amd64.img
      - version: '20210603'
        url: https://cloud-images.ubuntu.com/focal/20210603/focal-server-cloudimg-amd64.img
```
So that version 20210513.1 has visibility private and version 20210518 and 20210603 the visibility public, as set in the image configuration.
