### ISSUE TITLE
Custom properties are set falsely after adding a new image in the images.yml

### ISSUE THREAD

**Issue by tobfisch** [SovereignCloudStack/openstack-image-manager#169]
While testing the script I noticed that after adding a new image version to the `etc/images.yml`, custom_properties were missing for the newest image and the image rotated back had the wrong `internal_version`.

The `etc/images.yml` I used for testing: 
```
  - name: Ubuntu 20.04
    format: qcow2
    login: ubuntu
    min_disk: 8
    min_ram: 512
    status: active
    visibility: public
    multi: true
    meta:
      architecture: x86_64
      hw_disk_bus: scsi
      hw_rng_model: virtio
      hw_scsi_model: virtio-scsi
      hw_watchdog_action: reset
      os_distro: ubuntu
      os_version: '20.04'
    tags: []
    versions:
# first two versions already created with this script
      - version: '20210513.1'
        url: https://cloud-images.ubuntu.com/focal/20210513.1/focal-server-cloudimg-amd64.img
      - version: '20210518'
        url: https://cloud-images.ubuntu.com/focal/20210518/focal-server-cloudimg-amd64.img
# newly added version
      - version: '20210603'
        url: https://cloud-images.ubuntu.com/focal/20210603/focal-server-cloudimg-amd64.img
```

After executing the script, the images are successfully rotated, but Image `Ubuntu 20.04 (20210518)` has the wrong property: `
internal_version 20210603` instead of `20210518`
The new `Ubuntu 20.04` lacks properties which are usually set by the script  (e.g. `internal_version, `image_original_user`).
